### PR TITLE
Add support for @sap/eslint-plugin-cds

### PR DESCRIPTION
**Pull request by mnkiefer**
- Adds plugin and example for [@sap/eslint-plugin-cds](https://www.npmjs.com/package/@sap/eslint-plugin-cds)

@ota-meshi: Thank you for providing/hosting an *ESLint Online Playground* for other plugins! 👏 I was wondering:
 - Are the generated URLs guaranteed to remain *stable*?
   - If so, we would like to link our current rule documentation examples to your playground via an **Open in Playground** button (as it is done in the ESLint documentation, see [example for *curly* rule](https://eslint.org/docs/latest/rules/curly#options)).

### CODE REVIEW

**Comment by ota-meshi** [comment]
Thanks!

> Are the generated URLs guaranteed to remain stable?

I'm using Netlify on the free plan, so we can continue to use current domain as long as we don't exceed the free plan's bandwidth. And right now we have a lot of extra bandwidth.

image

If it's going to exceed the bandwidth of the free plan, I'll apply for an OSS plan, but I am not sure if it will be approved.
https://www.netlify.com/legal/open-source-policy/

**Comment by mnkiefer** [comment]
@ota-meshi: Finally getting back this this! ☺️ I still have a question with respect to the link evaluation.

For the [example for the CDS ESLint plugin](https://eslint-online-playground.netlify.app/#eNp9kLFOwzAQhl/l5AmkJlXXsDB06cyIGYxzCibO2bpzoaXqu3NxUKUgwWb9/u73d74YYb/Fk5tyxNb3YjpDbkLJziOIy613OTC2rymN8pbygyVLSCWUM9QMLpYARjzDYQ8AHRyo4ICsIIBiETXVOCbvYvjCHp4KBxrudrvdfYV6FM9/Q5W6WjIb06LEQIV9+y6JVLW+bQ2eClIv1nTwbE2OxyFQ96j2W91oy+jTNCmAvTUvm2WEjxHrQK2YE0qNTyQp4hxrKXNiayo/39/6pDguTf2DgNIcc0b2Tn7GPh2TNfOQOl9VWn9ydAP+Uu7xY495liKvLSuTZculLrqCoue1xkI0y6aNSv0H63XTj2vi5nf9BuU/qdU=), the playground link is determined based on the contents of the _source_, the _ESLint config_ and the _package.json_ files.

Would it be possible to compute these only the fly for other sources (i.e. other input example files) or would all of these examples have to be *checked in* to the repository to be referenced properly?

**Comment by ota-meshi** [comment]
Is the link format you are looking for like this?

<https://eslint-online-playground.netlify.app/#@sap/eslint-plugin-cds>

**Comment by mnkiefer** [comment]
> Is the link format you are looking for like this?
> 
> https://eslint-online-playground.netlify.app/#@sap/eslint-plugin-cds

Yes, this leads us to the playground with the [checked in example file](https://github.com/ota-meshi/eslint-online-playground/blob/main/src/examples/plugin-cds/src/example.cds.txt) that I mentioned.

My question was: If I would want to show another example (text in _src/example.cds_) to show the lint error of another plugin rule, is there a way that I could [encode](https://github.com/ota-meshi/eslint-online-playground/blob/3bd9bcc486350f62adb7509263b93b0ae3c507f1/src/utils/compress.ts#L3) this data into the URL or would have actually have to physically add the example to your repository?

**Comment by ota-meshi** [comment]
Are you saying you want to build the URL externally, but it's difficult because there's compression logic?
If so, would it solve the problem if the site could also accept uncompressed URL?

**Comment by mnkiefer** [comment]
> Are you saying you want to build the URL externally, but it's difficult because there's compression logic? If so, would it solve the problem if the site could also accept uncompressed URL?

Never mind, everything works as expected! 🎉 I just had a small bug in the script that computes the URLS based on the rules/examples sources. 🙃 

Thank you so much for your help and this awesome repo! I'm excited to link the Playground to the rule documentation buttons now and collect feedback from the users.

**Pull request merged**
